services:
  - type: web
    name: my-python-service
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py  
    branch: main
