name: Render Preview Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://personal-finance-tracker-1-0y9r.onrender.com
